Repository digitalkode/digitalkode, pull requests merged in 2020-10, with the labels that each got.

#74 Create Blog "cara-membuat-aplikasi-nest-js-pertama-kalian"
  content/blog/cara-membuat-aplikasi-nest-js-pertama-kalian.md
  static/images/uploads/1_czxaov35etfe545eiugfqq.png
  static/images/uploads/h8xg6re8hlz4ckmajshvvs5r2pj2-ct404tef.png
Labels: netlify-cms/pending_publish

#2 Create Authors "muhammad-faisal/_index"
  content/authors/muhammad-faisal/_index.md
Labels: netlify-cms/pending_publish

#37 Create HTML "html-5-series-11-html-video"
  content/html/html-5-series-11-html-video.md
  static/images/uploads/instagram-post-2-8-.jpg
Labels: netlify-cms/draft

#52 Create PHP "php-series-11-post-dan-get-request"
  content/php/php-series-11-post-dan-get-request.md
  static/images/uploads/php-series-11.png
Labels: netlify-cms/pending_review

#75 Create Blog "node-js-async-hooks-module-apaan-tuh"
  content/blog/node-js-async-hooks-module-apaan-tuh.md
  static/images/uploads/download.png
Labels: netlify-cms/draft

#77 Create CSS "css-series-4-height"
  content/CSS/css-series-4-height.md
  static/images/uploads/css-series-4.png
  static/images/uploads/screenshot_1.png
Labels: netlify-cms/pending_publish

#78 Update CSS "css-series-4-height"
  content/CSS/css-series-4-height.md
Labels: netlify-cms/pending_publish

#79 Update Authors "rizal/_index"
  content/authors/rizal/_index.md
Labels: netlify-cms/pending_publish

#80 Create CSS "css-series-5-width"
  content/CSS/css-series-5-width.md
  static/images/uploads/css-series-5.png
  static/images/uploads/css_button_4.png
Labels: netlify-cms/pending_publish
